name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      
      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
      - run: python run swap.py
